services:
  - type: web
    name: Online-classroom
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_SECRET_KEY
        value: your_secret_key
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_API_SECRET
        sync: false
      - key: LIVEKIT_URL
        sync: false
      - key: postgresql://liveclassroom_db_user:4LlknNrJn7DU6EHfwtg7sAugWROGLCVJ@dpg-d0nem3idbo4c73c3ldf0-a/liveclassroom_db
        fromDatabase:
          name: Liveclassroom
          property: connectionString
